---
deployment:
  tasks:
    - export FLASK_APP=index.py
    - /bin/bash -c 'source /home/encuestas25opol/public_html/application/venv/bin/activate && pip install -r requirements.txt'
    - touch /home/encuestas25opol/public_html/tmp/restart.txt
