---
deployment:
  tasks:
    - export FLASK_APP=index.py
    - /bin/bash -c 'source /home/CPANEL_ACCOUNT_NAME/FOLDER_NAME_PATH/venv/bin/activate && pip install -r requirements.txt'
    - touch /home/CPANEL_ACCOUNT_NAME/FOLDER_NAME_PATH/tmp/restart.txt
