dict_fields = {
    "name": "OctoberSurvey",
    "label": "Encuesta Octubre",
    "plural": "octobersurveys",
    'clazz_representation': '|id|,- |created_at|',
    "sort_field_results":"created_at|desc",
    "table_fields": " ID|id,Fecha|created_at",
    "search_fields": "id,created_at",
    "containers": {
        'OctoberSurveyContainer': {
            'type': 'row',
            'class': 'col-sm-12',
            'title': None,
            'connected_table': '',
            'connected_table_fields': '',
            'fields': {
                'age': {
                    'id': 'age',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Edad',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'gender': {
                    'id': 'gender',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Genero',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'religion': {
                    'id': 'religion',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Religión',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'county': {
                    'id': 'county',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Cantón',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'state': {
                    'id': 'state',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Provincia',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'education': {
                    'id': 'education',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Nivel educativo',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'party': {
                    'id': 'party',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Con qué partido se identifica',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'chavesSupport': {
                    'id': 'chavesSupport',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Apoya la gestión del Presidente Rodrigo Chaves?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'chavesScale': {
                    'id': 'chavesScale',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Del 1 al 10, como califica la labor de Rodrigo Chaves?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'nationalElection': {
                    'id': 'nationalElection',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Si las elecciones fueran hoy, ¿por quién votaría para presidente?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'nationalElectionSecond': {
                    'id': 'nationalElectionSecond',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Cuál sería su segunda opción, de votación?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'congressParty': {
                    'id': 'congressParty',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Si las elecciones fueran hoy, ¿por cuál partido votaría para diputados?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'conoceJuanCarlos': {
                    'id': 'conoceJuanCarlos',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Conoce a Juan Carlos Hidalgo?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'opinionJuanCarlos': {
                    'id': 'opinionJuanCarlos',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Cuál es su opinión sobre Juan Carlos Hidalgo?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'conoceWalter': {
                    'id': 'conoceWalter',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Conoce a Walter Ruben?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'opinionWalter': {
                    'id': 'opinionWalter',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Cuál es su opinión sobre Walter Ruben?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'conoceLauraFernandez': {
                    'id': 'conoceLauraFernandez',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Conoce a Laura Fernandez?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'opinionLauraFernandez': {
                    'id': 'opinionLauraFernandez',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Cuál es su opinión sobre Laura Fernandez?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'conoceNataliaDiaz': {
                    'id': 'conoceNataliaDiaz',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Conoce a Natalia Diaz?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'opinionNataliaDiaz': {
                    'id': 'opinionNataliaDiaz',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Cuál es su opinión sobre Natalia Diaz?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'conoceArielRobles': {
                    'id': 'conoceArielRobles',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Conoce a Ariel Robles?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'opinionArielRobles': {
                    'id': 'opinionArielRobles',
                    'type': 'String',
                    'maxlength': '',
                    'label': '¿Cuál es su opinión sobre Ariel Robles?',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'contact': {
                    'id': 'contact',
                    'type': 'String',
                    'maxlength': '',
                    'label': 'Contacto',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                },
                'userCreation': {
                    'id': 'userCreation',
                    'type': 'createdby',
                    'maxlength': '',
                    'label': 'Encuestador',
                    'input': 'text',
                    'class': '',
                    'select_options': '',
                    'connected_table': '',
                    'required': '',
                    'hidden': '',
                    'defaultValue': ''
                }
            }
        }
    }
}
