# -*- coding: utf-8 -*- 

from . import surveyoctober
from . import surveyoctobertwo
from . import surveynovember
from . import surveynovembertwo

def get_list_by_name():
    return {'surveyoctober': {'id': 1, 'name': 'surveyoctober', 'classname': 'Surveyoctober', 'filename': 'surveyoctober.py', 'label': 'Encuesta Octubre 2025', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctober', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at', 'search_fields': 'id,created_at', 'clazz_representation': '|created_by|-, |created_at|'}, 'surveyoctobertwo': {'id': 2, 'name': 'surveyoctobertwo', 'classname': 'Surveyoctobertwo', 'filename': 'surveyoctobertwo.py', 'label': 'Encuesta Octubre 2025 - EN1025-2', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctoberTwo', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Ebais|ebais,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,ebais,education,gender,nationalElection,party,religion,state,willvote', 'clazz_representation': ' |createdby_id|-, |created_at|'}, 'surveynovember': {'id': 3, 'name': 'surveynovember', 'classname': 'Surveynovember', 'filename': 'surveynovember.py', 'label': 'Encuesta Electoral Nacional OPol - Noviembre 2025 - EENO-1125', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysNovember', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Apoya a Chaves|chavesSupport,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,chavesSupport,education,gender,nationalElection,party,religion,state,willvote', 'clazz_representation': ' |createdby_id|-, |created_at|'}, 'surveynovembertwo': {'id': 4, 'name': 'surveynovembertwo', 'classname': 'Surveynovembertwo', 'filename': 'surveynovembertwo.py', 'label': 'Tercera Encuesta Electoral Nacional OPol - Noviembre 2025 - EENO-1125-2', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysNovemberTwo', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Apoya a Chaves|chavesSupport,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote,Escala|voteScale', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,chavesSupport,education,gender,nationalElection,party,religion,state,willvote,voteScale', 'clazz_representation': ' |createdby_id|-, |created_at|'}}


def get_list_by_id():
    return {1: {'id': 1, 'name': 'surveyoctober', 'classname': 'Surveyoctober', 'filename': 'surveyoctober.py', 'label': 'Encuesta Octubre 2025', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctober', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at', 'search_fields': 'id,created_at', 'clazz_representation': '|created_by|-, |created_at|'}, 2: {'id': 2, 'name': 'surveyoctobertwo', 'classname': 'Surveyoctobertwo', 'filename': 'surveyoctobertwo.py', 'label': 'Encuesta Octubre 2025 - EN1025-2', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctoberTwo', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Ebais|ebais,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,ebais,education,gender,nationalElection,party,religion,state,willvote', 'clazz_representation': ' |createdby_id|-, |created_at|'}, 3: {'id': 3, 'name': 'surveynovember', 'classname': 'Surveynovember', 'filename': 'surveynovember.py', 'label': 'Encuesta Electoral Nacional OPol - Noviembre 2025 - EENO-1125', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysNovember', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Apoya a Chaves|chavesSupport,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,chavesSupport,education,gender,nationalElection,party,religion,state,willvote', 'clazz_representation': ' |createdby_id|-, |created_at|'}, 4: {'id': 4, 'name': 'surveynovembertwo', 'classname': 'Surveynovembertwo', 'filename': 'surveynovembertwo.py', 'label': 'Tercera Encuesta Electoral Nacional OPol - Noviembre 2025 - EENO-1125-2', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysNovemberTwo', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Apoya a Chaves|chavesSupport,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote,Escala|voteScale', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,chavesSupport,education,gender,nationalElection,party,religion,state,willvote,voteScale', 'clazz_representation': ' |createdby_id|-, |created_at|'}}
