# -*- coding: utf-8 -*- 

from . import surveyoctober
from . import surveyoctobertwo

def get_list_by_name():
    return {'surveyoctober': {'id': 1, 'name': 'surveyoctober', 'classname': 'Surveyoctober', 'filename': 'surveyoctober.py', 'label': 'Encuesta Octubre 2025', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctober', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at', 'search_fields': 'id,created_at', 'clazz_representation': '|created_by|-, |created_at|'}, 'surveyoctobertwo': {'id': 2, 'name': 'surveyoctobertwo', 'classname': 'Surveyoctobertwo', 'filename': 'surveyoctobertwo.py', 'label': 'Encuesta Octubre 2025 - EN1025-2', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctoberTwo', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Ebais|ebais,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,ebais,education,gender,nationalElection,party,religion,state,willvote', 'clazz_representation': ' |createdby_id|-, |created_at|'}}


def get_list_by_id():
    return {1: {'id': 1, 'name': 'surveyoctober', 'classname': 'Surveyoctober', 'filename': 'surveyoctober.py', 'label': 'Encuesta Octubre 2025', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctober', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at', 'search_fields': 'id,created_at', 'clazz_representation': '|created_by|-, |created_at|'}, 2: {'id': 2, 'name': 'surveyoctobertwo', 'classname': 'Surveyoctobertwo', 'filename': 'surveyoctobertwo.py', 'label': 'Encuesta Octubre 2025 - EN1025-2', 'tag': None, 'treeView': None, 'template': None, 'plural': 'surveysOctoberTwo', 'sort_field_results': 'created_at|desc', 'table_fields': 'ID|id,Fecha|created_at,Edad|age,Categoría|category,Diputado|congress,Cantón|county,Usuario|createdby_id,Ebais|ebais,Educación|education,Género|gender,Presidencia|nationalElection,Partido|party,Religión|religion,Provincia|state,Votará|willvote', 'search_fields': 'id,created_at,age,category,congress,contact,county,createdby_id,ebais,education,gender,nationalElection,party,religion,state,willvote', 'clazz_representation': ' |createdby_id|-, |created_at|'}}
