"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-05-23 18:46:52

Revision ID: 055f3693911a
Revises: 41810d85846d
Create Date: 2025-05-23 18:47:00.462707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055f3693911a'
down_revision = '41810d85846d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barvasurvey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('barvaSupport', sa.String(length=255), nullable=True),
    sa.Column('barvaScale', sa.String(length=255), nullable=True),
    sa.Column('chavesConoce', sa.String(length=255), nullable=True),
    sa.Column('chavesOpinion', sa.String(length=255), nullable=True),
    sa.Column('jorgeConoce', sa.String(length=255), nullable=True),
    sa.Column('jorgeOpinion', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_barvasurvey_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_barvasurvey_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barvasurvey')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barvasurvey')
    # ### end Alembic commands ###
