"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-03-15 15:11:00

Revision ID: 1710eb22bf18
Revises: 8e49c41a4cd5
Create Date: 2025-03-15 15:11:11.806063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1710eb22bf18'
down_revision = '8e49c41a4cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymarch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymarch', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
