"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-06-26 02:55:26

Revision ID: 1dc760963b9f
Revises: a904bfb56210
Create Date: 2025-06-26 02:55:38.443365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc760963b9f'
down_revision = 'a904bfb56210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('junesurvey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('chavesSupport', sa.String(length=255), nullable=True),
    sa.Column('nationalElection', sa.String(length=255), nullable=True),
    sa.Column('aguilarConoce', sa.String(length=255), nullable=True),
    sa.Column('aguilarOpinion', sa.String(length=255), nullable=True),
    sa.Column('arielConoce', sa.String(length=255), nullable=True),
    sa.Column('arielOpinion', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_junesurvey_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_junesurvey_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_junesurvey')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('junesurvey')
    # ### end Alembic commands ###
