"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-08-01 00:04:14

Revision ID: 235e86e77126
Revises: 37c9e4301c5e
Create Date: 2025-08-01 00:04:21.495607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235e86e77126'
down_revision = '37c9e4301c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('augustsurvey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('augustsurvey', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
