"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-07-31 23:35:39

Revision ID: 37c9e4301c5e
Revises: 86c28aee37c7
Create Date: 2025-07-31 23:35:47.229886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c9e4301c5e'
down_revision = '86c28aee37c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('augustsurvey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('chavesSupport', sa.String(length=255), nullable=True),
    sa.Column('nationalElection', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_augustsurvey_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_augustsurvey_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_augustsurvey')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('augustsurvey')
    # ### end Alembic commands ###
