"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-09-25 02:35:43

Revision ID: 408c46007d98
Revises: 4f40641de5b9
Create Date: 2025-09-25 02:35:50.743232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408c46007d98'
down_revision = '4f40641de5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('octobersurvey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('religion', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('chavesSupport', sa.String(length=255), nullable=True),
    sa.Column('chavesScale', sa.String(length=255), nullable=True),
    sa.Column('nationalElection', sa.String(length=255), nullable=True),
    sa.Column('nationalElectionSecond', sa.String(length=255), nullable=True),
    sa.Column('congressParty', sa.String(length=255), nullable=True),
    sa.Column('conoceJuanCarlos', sa.String(length=255), nullable=True),
    sa.Column('opinionJuanCarlos', sa.String(length=255), nullable=True),
    sa.Column('conoceWalter', sa.String(length=255), nullable=True),
    sa.Column('opinionWalter', sa.String(length=255), nullable=True),
    sa.Column('conoceLauraFernandez', sa.String(length=255), nullable=True),
    sa.Column('opinionLauraFernandez', sa.String(length=255), nullable=True),
    sa.Column('conoceNataliaDiaz', sa.String(length=255), nullable=True),
    sa.Column('opinionNataliaDiaz', sa.String(length=255), nullable=True),
    sa.Column('conoceArielRobles', sa.String(length=255), nullable=True),
    sa.Column('opinionArielRobles', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_octobersurvey_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_octobersurvey_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_octobersurvey')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('octobersurvey')
    # ### end Alembic commands ###
