"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-04-04 20:27:08

Revision ID: 41810d85846d
Revises: 477447d3ac6a
Create Date: 2025-04-04 20:27:14.510546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41810d85846d'
down_revision = '477447d3ac6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plnday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('alvaroramos', sa.Integer(), nullable=True),
    sa.Column('gilberthjimenez', sa.Integer(), nullable=True),
    sa.Column('carolinadelgado', sa.Integer(), nullable=True),
    sa.Column('marvintaylor', sa.Integer(), nullable=True),
    sa.Column('blank', sa.Integer(), nullable=True),
    sa.Column('nulled', sa.Integer(), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_plnday_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_plnday_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plnday')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plnday')
    # ### end Alembic commands ###
