"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-04-04 11:34:24

Revision ID: 477447d3ac6a
Revises: db71a5d96eeb
Create Date: 2025-04-04 11:34:30.696941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477447d3ac6a'
down_revision = 'db71a5d96eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymarchtwo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymarchtwo', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
