"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-08-28 14:11:44

Revision ID: 4f40641de5b9
Revises: 71d7ba7e5bff
Create Date: 2025-08-28 14:11:51.193279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f40641de5b9'
down_revision = '71d7ba7e5bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('septembersurvey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('septembersurvey', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###
