"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-02-25 04:33:14

Revision ID: 54255175fa4e
Revises: 9ad145fc72d5
Create Date: 2025-02-25 04:33:20.736356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54255175fa4e'
down_revision = '9ad145fc72d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
