"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-06-14 00:25:59

Revision ID: 6237ba5ba8de
Revises: 055f3693911a
Create Date: 2025-06-14 00:26:06.564077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6237ba5ba8de'
down_revision = '055f3693911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turrialbasurvey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('conoceCarlos', sa.String(length=255), nullable=True),
    sa.Column('opinionCarlos', sa.String(length=255), nullable=True),
    sa.Column('conoceRodrigoChaves', sa.String(length=255), nullable=True),
    sa.Column('opinionRodrigoChaves', sa.String(length=255), nullable=True),
    sa.Column('apoyaAlcalde', sa.String(length=255), nullable=True),
    sa.Column('muniScale', sa.String(length=255), nullable=True),
    sa.Column('apoyaRodrigoChaves', sa.String(length=255), nullable=True),
    sa.Column('chavesParty', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_turrialbasurvey_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_turrialbasurvey_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turrialbasurvey')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turrialbasurvey')
    # ### end Alembic commands ###
