"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-08-28 13:18:50

Revision ID: 71d7ba7e5bff
Revises: ab7a8713d773
Create Date: 2025-08-28 13:18:56.738157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d7ba7e5bff'
down_revision = 'ab7a8713d773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('septembersurvey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('willvote', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('septembersurvey', schema=None) as batch_op:
        batch_op.drop_column('willvote')

    # ### end Alembic commands ###
