"""Crea clase de historial

Revision ID: 827040124ed7
Revises: 408c46007d98
Create Date: 2025-09-25 03:16:20.731144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827040124ed7'
down_revision = '408c46007d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataRequest', sa.Text(), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_historial_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_historial_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    # ### end Alembic commands ###
