"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-07-04 09:42:52

Revision ID: 86c28aee37c7
Revises: 1dc760963b9f
Create Date: 2025-07-04 09:43:10.076645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86c28aee37c7'
down_revision = '1dc760963b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('junesurvey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('apoyaAlcalde', sa.String(length=255), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('junesurvey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('apoyaAlcalde')
        batch_op.drop_column('county')

    # ### end Alembic commands ###
