"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-03-14 18:51:12

Revision ID: 8e49c41a4cd5
Revises: b7de3b114aa0
Create Date: 2025-03-14 18:51:19.233425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e49c41a4cd5'
down_revision = 'b7de3b114aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveymarch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('chavesParty', sa.String(length=255), nullable=True),
    sa.Column('plnElections', sa.String(length=255), nullable=True),
    sa.Column('plnCandidate', sa.String(length=255), nullable=True),
    sa.Column('generalElections', sa.String(length=255), nullable=True),
    sa.Column('chavesSupport', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_surveymarch_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_surveymarch_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveymarch'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveymarch')
    # ### end Alembic commands ###
