"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-03-28 20:45:22

Revision ID: 93a9bdd8899d
Revises: 1710eb22bf18
Create Date: 2025-03-28 20:45:28.686308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a9bdd8899d'
down_revision = '1710eb22bf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveymarchtwo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('plnElections', sa.String(length=255), nullable=True),
    sa.Column('plnScale', sa.String(length=255), nullable=True),
    sa.Column('plnCandidate', sa.String(length=255), nullable=True),
    sa.Column('generalElections', sa.String(length=255), nullable=True),
    sa.Column('chavesSupport', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_surveymarchtwo_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_surveymarchtwo_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveymarchtwo')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveymarchtwo')
    # ### end Alembic commands ###
