"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-02-25 02:29:30

Revision ID: 9ad145fc72d5
Revises: 
Create Date: 2025-02-25 02:29:38.158289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad145fc72d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('conoceRodrigoChaves', sa.String(length=255), nullable=True),
    sa.Column('opinionRodrigoChaves', sa.String(length=255), nullable=True),
    sa.Column('conoceMauricioBatalla', sa.String(length=255), nullable=True),
    sa.Column('opinionMauricioBatalla', sa.String(length=255), nullable=True),
    sa.Column('conoceLauraFernandez', sa.String(length=255), nullable=True),
    sa.Column('opinionLauraFernandez', sa.String(length=255), nullable=True),
    sa.Column('conoceAlvaroRamos', sa.String(length=255), nullable=True),
    sa.Column('opinionAlvaroRamos', sa.String(length=255), nullable=True),
    sa.Column('conoceGilbertJimenez', sa.String(length=255), nullable=True),
    sa.Column('opinionGilbertJimenez', sa.String(length=255), nullable=True),
    sa.Column('conoceCarolinaDelgado', sa.String(length=255), nullable=True),
    sa.Column('opinionCarolinaDelgado', sa.String(length=255), nullable=True),
    sa.Column('conoceMarvinTaylor', sa.String(length=255), nullable=True),
    sa.Column('opinionMarvinTaylor', sa.String(length=255), nullable=True),
    sa.Column('conoceRolandoArayaMonge', sa.String(length=255), nullable=True),
    sa.Column('opinionRolandoArayaMonge', sa.String(length=255), nullable=True),
    sa.Column('chavesParty', sa.String(length=255), nullable=True),
    sa.Column('chavesCandidate', sa.String(length=255), nullable=True),
    sa.Column('plnElections', sa.String(length=255), nullable=True),
    sa.Column('plnCandidate', sa.String(length=255), nullable=True),
    sa.Column('generalElections', sa.String(length=255), nullable=True),
    sa.Column('chavesSupport', sa.String(length=255), nullable=True),
    sa.Column('chavesScale', sa.String(length=255), nullable=True),
    sa.Column('createdby_id', sa.Integer(), nullable=True),
    sa.Column('modifiedby_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdby_id'], ['user.id'], name=op.f('fk_survey_createdby_id_user')),
    sa.ForeignKeyConstraint(['modifiedby_id'], ['user.id'], name=op.f('fk_survey_modifiedby_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    # ### end Alembic commands ###
