"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-06-14 00:26:52

Revision ID: a904bfb56210
Revises: 6237ba5ba8de
Create Date: 2025-06-14 00:26:58.101344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a904bfb56210'
down_revision = '6237ba5ba8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turrialbasurvey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turrialbasurvey', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
