"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-02-26 00:37:46

Revision ID: b7de3b114aa0
Revises: 54255175fa4e
Create Date: 2025-02-26 00:37:51.582248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7de3b114aa0'
down_revision = '54255175fa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partyAndChaves', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('partyAndChaves')

    # ### end Alembic commands ###
