"""Actualizacion de Base de datos hecha por vane.valverdesantos@gmail.com a las: 2025-03-28 22:17:16

Revision ID: db71a5d96eeb
Revises: 93a9bdd8899d
Create Date: 2025-03-28 22:17:22.086038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db71a5d96eeb'
down_revision = '93a9bdd8899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymarchtwo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymarchtwo', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
